exports.types = {
    jpg: {
        extension: 'jpg',
        outputOptions: [
            '-pix_fmt yuv422p',
        ],
        urlSupport: true,
    },
    m4a: {
        extension: 'm4a',
        outputOptions: [
            '-codec:a libfdk_aac',
        ],
        urlSupport: true,
    },
    mp3: {
        extension: 'mp3',
        outputOptions: [
            '-codec:a libmp3lame',
        ],
        urlSupport: true,
    },
    mp4: {
        extension: 'mp4',
        outputOptions: [
            '-codec:v libx264',
            '-profile:v high',
            '-r 15',
            '-crf 23',
            '-preset ultrafast',
            '-b:v 500k',
            '-maxrate 500k',
            '-bufsize 1000k',
            '-vf scale=-2:640',
            '-threads 8',
            '-codec:a libfdk_aac',
            '-b:a 128k',
        ],
        urlSupport: true,
    },
    'audio-image-mp4': {
        extension: 'mp4',
        outputOptions: [
            '-codec:v libx264',
            '-profile:v high',
            '-r 30',
            '-crf 23',
            '-preset ultrafast',
            '-b:v 1000k',
            '-maxrate 1000k',
            '-bufsize 2000k',
            '-vf scale=-2:720,format=yuv420p',
            '-threads 8',
            '-codec:a libfdk_aac',
            '-b:a 128k',
        ],
        multiFile: true,
        requires: ['audio', 'image'],
        urlSupport: true,
    },
    'audio-duration': {
        extension: 'txt',
        ffprobe: true,
        outputOptions: [
            '-v', 'error',
            '-show_entries', 'format=duration',
            '-of', 'default=noprint_wrappers=1:nokey=1'
        ],
        urlSupport: true,
    },
    'audio-mix': {
        extension: 'mp3',
        multiFile: true,
        requires: ['background', 'vocals'],
        complexFilter: true,
        outputOptions: [
            '-codec:a', 'libmp3lame',
            '-b:a', '192k',
        ],
        urlSupport: true,
    },
    'compilation': {
        extension: 'mp4',
        multiFile: true,
        isCompilation: true,
        outputOptions: [
            '-codec:v libx264',
            '-profile:v high',
            '-crf 23',
            '-preset medium',
            '-codec:a aac',
            '-b:a 128k',
            '-ar 44100',
            '-movflags +faststart',
        ],
        urlSupport: true,
    },
    'compilation-simple': {
        extension: 'mp4',
        multiFile: true,
        isCompilationSimple: true,
        outputOptions: [
            '-codec:v libx264',
            '-profile:v high',
            '-crf 23',
            '-preset medium',
            '-codec:a aac',
            '-b:a 128k',
            '-ar 44100',
            '-movflags +faststart',
        ],
        urlSupport: true,
    },
};
